title: "A Programmer's Perspective"
author: "Woo Jia Hao"
description: "My personal blog where I share my personal thoughts and progress on programming here."
lang: "en"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 8                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false         # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
dark_theme: false            # enable dark mode
dark_header: false           # keep the header dark

navigation:                  # (optional) site navigation in the header
  - index.html
  - about.md
  - README.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/woojiahao"
  envelope: "mailto:woojiahao1234@gmail.com"
  linkedin: "https://www.linkedin.com/in/woo-jia-hao-089346155/"
  twitter: "https://twitter.com/devchill1"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
